# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

#development:
#  api_key: deef555a0160a4a781f27a45c8d979e5
#  secret_key: 012ccf3e849f7b4b1fc5b3275e1412d4
#  canvas_page_name: ror_book_dan
#  callback_url: http://75.162.182.186:3000
#  tunnel:
#    public_host_username: 
#    public_host: 75.162.182.186
#    public_port: 3000
#    local_port: 3000

development:    
	api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

test:
  api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000