# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

development:
  api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

test:
  api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000

production:
  api_key: d7543973dc05d3ace05030ae3acd1a12
  secret_key: f946374dd0f06acf57df5b3092b168e2
  canvas_page_name: /rorbook/
  callback_url: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000